### ISSUE TITLE
Git Clone + Checkout functionality on server

### ISSUE THREAD

**Issue by modnikhil** [jsjolen/smallest-java-ci#12]
When our server receives a POST request from a GitHub webhook, our serve should pull the newest updates from the remote repository, and checkout the branch which had changes made to it. Both repo name and commit SHA should be visible in the webhook payload

**Comment by jsjolen** [comment]
Branch name isn't necessary, use the SHA-1 hash instead (you can checkout that). It's true that you'll need the repo URL though :-). Look into a previous issue to see links to the documentation regarding that.

**Comment by modnikhil** [comment]
Yes! Thanks for clarifying, I'll update the issue. Realized that when I reviewed the PullRequestEvent PR.

**Comment by jsjolen** [comment]
You can look at GradleComm to see how to do communication.
